# Generated by Django 5.0.3 on 2024-03-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_publish_d4ce3b_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='publish',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='blog.author'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['published_date'], name='blog_commen_publish_15b713_idx'),
        ),
    ]
